parameters:
  buildConfiguration: 'Release'

steps:
- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info - ${{ parameters.buildConfiguration }}'
  workingDirectory: ./

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build - ${{ parameters.buildConfiguration }}'
   
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '${{ parameters.buildConfiguration }}'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'

  